### ISSUE TITLE
Error: EXDEV, cross-device link not permitted 

### ISSUE THREAD

**Issue by rajeshvishnani** [freshdesk/mobihelp-phonegap#1]
Hello, 

I cloned this in git and then tried to install in cordova app but it gives following error. please suggest weather this supports in cordova or not.

Fetching plugin "https://github.com/acashjos/mobihelp-cordova.git" via git clone

Repository "https://github.com/acashjos/mobihelp-cordova.git" checked out to git
 ref "master".
shell.js: internal error
Error: EXDEV, cross-device link not permitted 'C:\Users\RAJESH~1\AppData\Local\T
emp\git\1440671409587\ant.properties'
    at Error (native)
    at Object.fs.renameSync (fs.js:636:18)
    at C:\Users\Rajesh Vishnani\AppData\Roaming\npm\node_modules\cordova\node_mo
dules\cordova-lib\node_modules\shelljs\src\mv.js:77:8
    at Array.forEach (native)
    at Object._mv (C:\Users\Rajesh Vishnani\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\node_modules\shelljs\src\mv.js:53:11)
    at Object.mv (C:\Users\Rajesh Vishnani\AppData\Roaming\npm\node_modules\cord
ova\node_modules\cordova-lib\node_modules\shelljs\src\common.js:186:23)
    at C:\Users\Rajesh Vishnani\AppData\Roaming\npm\node_modules\cordova\node_mo
dules\cordova-lib\src\plugman\util\plugins.js:53:19
    at _fulfilled (C:\Users\Rajesh Vishnani\AppData\Roaming\npm\node_modules\cor
dova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Rajesh Vishnani\AppData\Roaming\npm\n
ode_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Rajesh Vishnani\AppData\Roaming
\npm\node_modules\cordova\node_modules\q\q.js:749:13)

**Comment by SatheeshJM** [comment]
@rajeshvishnani 
The git link which you have given is not the official Mobihelp plugin..
Please use the git link of this project to install the official version 
`cordova plugin add https://github.com/freshdesk/mobihelp-phonegap.git`

**Comment by rajeshvishnani** [comment]
Hi @SatheeshJM ,

I used above link but now i get this error.

Fetching plugin "https://github.com/freshdesk/mobihelp-phonegap.git" via git clo
ne
Repository "https://github.com/freshdesk/mobihelp-phonegap.git" checked out to g
it ref "master".
shell.js: internal error
Error: EXDEV, cross-device link not permitted 'C:\Users\RAJESH~1\AppData\Local\T
emp\git\1440672263927\plugin.xml'
    at Error (native)
    at Object.fs.renameSync (fs.js:636:18)
    at C:\Users\Rajesh Vishnani\AppData\Roaming\npm\node_modules\cordova\node_mo
dules\cordova-lib\node_modules\shelljs\src\mv.js:77:8
    at Array.forEach (native)
    at Object._mv (C:\Users\Rajesh Vishnani\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\node_modules\shelljs\src\mv.js:53:11)
    at Object.mv (C:\Users\Rajesh Vishnani\AppData\Roaming\npm\node_modules\cord
ova\node_modules\cordova-lib\node_modules\shelljs\src\common.js:186:23)
    at C:\Users\Rajesh Vishnani\AppData\Roaming\npm\node_modules\cordova\node_mo
dules\cordova-lib\src\plugman\util\plugins.js:53:19
    at _fulfilled (C:\Users\Rajesh Vishnani\AppData\Roaming\npm\node_modules\cor
dova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Rajesh Vishnani\AppData\Roaming\npm\n
ode_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Rajesh Vishnani\AppData\Roaming
\npm\node_modules\cordova\node_modules\q\q.js:749:13)

**Comment by SatheeshJM** [comment]
What version of Cordova are you using?  Apparently there was a bug in 5.1.0+

**Comment by rajeshvishnani** [comment]
@SatheeshJM , I am using Cordova 5.1.1

**Comment by SatheeshJM** [comment]
Can you try updating cordova? 
This fix is supposed to have been fixed in 5.2.0
https://issues.apache.org/jira/browse/CB-9212

**Comment by rajeshvishnani** [comment]
@SatheeshJM thanks i did update the cordova version to 5.2.0 and the plugin is installed successfully.
